spring.application.name=gestionStock-backend-mobile

# DATABASE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionstock_db
spring.datasource.username=postgres_bd
spring.datasource.password=postgres_bd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8083
server.forward-headers-strategy=native

# Keycloak/OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
jwt.auth.converter.principal-attribute=preferred_username
jwt.auth.converter.resource-id=myclient
keycloak.realm=myrealm

# --- Configuration Keycloak pour l'API Admin (facultatif si le backend a besoin d'appeler l'API Keycloak) ---
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=myclient
keycloak.public-client=true
keycloak.bearer-only=true

# Configuration Nextcloud (pour servir les images des pièces)
# En Docker, les variables d'environnement ont la priorité
nextcloud.url=${NEXTCLOUD_URL:http://localhost:8082}
nextcloud.username=${NEXTCLOUD_USERNAME:admin}
nextcloud.password=${NEXTCLOUD_PASSWORD:StockMasters123}
nextcloud.base-path=${NEXTCLOUD_BASE_PATH:/remote.php/dav/files/admin}
nextcloud.documents-folder=${NEXTCLOUD_DOCUMENTS_FOLDER:pieces_images}
